[package]
name = "hotel_import"
version = "0.1.0"
authors = ["Joshua Bowles <jbowayles@gmail.com>"]
edition = "2018"

[dependencies]
fspec = {path="fspec"}
dbcon = {path="dbcon"}
migrant_lib = "0.20.0"
chrono = "0.4"